service:
  name: trainmate
  publish: false # Do not publish updates to serverless.com, it's none of their business

provider:
  name: aws
  timeout: 600
  runtime: nodejs8.10
  region: ap-southeast-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "rds-data:ExecuteSql"
      Resource:
        - "*"
    - Effect: Allow
      Action:
        - "ssm:GetParametersByPath"
        - "ssm:GetParameter"
      Resource:
        - "*"

functions:
  api:
    handler: api.handler
    environment:
      PGUSER: postgres
      PGDATABASE: trainmate
      PGHOST: trainmate-dev.cluster-cklwzjsk3iwv.ap-southeast-2.rds.amazonaws.com
      PGPASSWORD: ${ssm:trainmateDBPassword}
    events:
      - http:
          path: /
          method: get
  ingest:
    handler: ingest.handler